spring:
  cloud:
    gateway:
      routes:
        - id: r1 # route 1
          uri: http://localhost:8080/ # L'URI cible pour cette route
          predicates:
            - Path=/customers/**
        - id: r2 # route 2
          uri: http://localhost:8082/ # L'URI cible pour cette route
          predicates:
            - Path=/products/**
